create table entrega
(
    id                       BIGINT generated by default as identity NOT NULL,
    cliente_id               BIGINT                                  NOT NULL,
    taxa                     DECIMAL(10, 2)                          NOT NULL,
    status                   VARCHAR(20)                             NOT NULL,
    data_pedido              TIMESTAMP                               NOT NULL,
    data_finalizacao         TIMESTAMP,

    destinatario_nome        VARCHAR(60)                             NOT NULL,
    destinatario_logradouro  VARCHAR(255)                            NOT NULL,
    destinatario_numero      VARCHAR(30)                             NOT NULL,
    destinatario_complemento VARCHAR(60)                             NOT NULL,
    destinatario_bairro      VARCHAR(30)                             NOT NULL,

    primary key (id)
);

alter table entrega
    add constraint fk_entrega_cliente
        foreign key (cliente_id) references cliente (id);